---
title: "Tarea 2 11/22 Modelaje"
author: "Francisco Alfonso Perez Storms"
date: "1/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library(deSolve)
```

Modelo SIR
Con demografía
```{r}
SIR <- function(t, state, parameters) {
with(as.list(c(state, parameters)), { 
       dS<- nu*(S+I+R) -beta*S*I -mu*S
       dI<- beta*S*I -gama*I -muI*I
       dR<- gama*I -mu*R
        list(c(dS, dI, dR))
      })
}
```

```{r}
pars <- c(nu=.2, beta= 4, gama = 2, mu=.17, muI=.2)  
condiciones_iniciales <- c(S =0, I=999,R=0)
tiempo <- seq(0, 2.5, by = 0.001)
out <- ode(condiciones_iniciales, tiempo, SIR, pars) 

matplot(out[ , 1], out[ , 2:4], type = "l", xlab = "tiempo", ylab = "Población",
main = "SIR", lwd = 2)
legend("topright", c("Susceptible", "Infectado","Recuperado"), col = 1:3,lty=1:3,cex=0.5)
```

Modelo SEIR
Con demografía e inmunidad de expuestos
```{r}
SEIR <- function(t, state, parameters) {
with(as.list(c(state, parameters)), { 
       dS<- nu*(S+I+R+E) -beta*S*I -mu*S
       dE<- beta*S*I -delta*E -epsilon*E -mu*E
       dI<- delta*E -gama*I -muI*I
       dR<- gama*I + epsilon*E -mu*R
        list(c(dS, dE, dI, dR))
      })
}
```

```{r}
pars2 <- c(nu=.2, beta= 2, delta=1/15, epsilon=.005, gama =1, mu=.19, muI=.2)  
condiciones_iniciales2 <- c(S =0, E=0, I=1000 ,R=0)
tiempo2 <- seq(0, 4, by = 0.001)
out2 <- ode(condiciones_iniciales2, tiempo2, SEIR, pars2) 

matplot(out2[ , 1], out2[ , 2:4], type = "l", xlab = "tiempo", ylab = "Población",
main = "SEIR", lwd = 2)
legend("topright", c("Susceptible", "Expuesto", "Infectado","Recuperado"), col = 1:3,lty=1:3,cex=0.5)
```


Modelo SEIRS
Con demografía e inmunidad de expuestos
```{r}
SEIRS <- function(t, state, parameters) {
with(as.list(c(state, parameters)), { 
       dS<- nu*(S+I+R+E) + alfa*R -beta*S*I -mu*S
       dE<- beta*S*I -delta*E -epsilon*E -mu*E
       dI<- delta*E -gama*I -muI*I
       dR<- gama*I + epsilon*E -mu*R -alfa*R
        list(c(dS, dE, dI, dR))
      })
}
```

```{r}
pars3 <- c(nu=.2, beta= 2, alfa=1/60, delta=1/15, epsilon=.005, gama = 2, mu=.19, muI=.2)  
condiciones_iniciales3 <- c(S =0, E=0, I=1000 ,R=0)
tiempo3 <- seq(0, 8, by = 0.001)
out3 <- ode(condiciones_iniciales3, tiempo3, SEIRS, pars3) 

matplot(out3[ , 1], out2[ , 2:4], type = "l", xlab = "tiempo", ylab = "Población",
main = "SEIRS", lwd = 2)
legend("topright", c("Susceptible", "Expuesto", "Infectado","Recuperado"), col = 1:3,lty=1:3,cex=0.5)
```